/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd;

public class SF_VIRTUAL_IO {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SF_VIRTUAL_IO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SF_VIRTUAL_IO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsndfileJNI.delete_SF_VIRTUAL_IO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGet_filelen(SWIGTYPE_p_f_p_void____int64 value) {
    libsndfileJNI.SF_VIRTUAL_IO_get_filelen_set(swigCPtr, this, SWIGTYPE_p_f_p_void____int64.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void____int64 getGet_filelen() {
    long cPtr = libsndfileJNI.SF_VIRTUAL_IO_get_filelen_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void____int64(cPtr, false);
  }

  public void setSeek(SWIGTYPE_p_f___int64_int_p_void____int64 value) {
    libsndfileJNI.SF_VIRTUAL_IO_seek_set(swigCPtr, this, SWIGTYPE_p_f___int64_int_p_void____int64.getCPtr(value));
  }

  public SWIGTYPE_p_f___int64_int_p_void____int64 getSeek() {
    long cPtr = libsndfileJNI.SF_VIRTUAL_IO_seek_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f___int64_int_p_void____int64(cPtr, false);
  }

  public void setRead(SWIGTYPE_p_f_p_void___int64_p_void____int64 value) {
    libsndfileJNI.SF_VIRTUAL_IO_read_set(swigCPtr, this, SWIGTYPE_p_f_p_void___int64_p_void____int64.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void___int64_p_void____int64 getRead() {
    long cPtr = libsndfileJNI.SF_VIRTUAL_IO_read_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void___int64_p_void____int64(cPtr, false);
  }

  public void setWrite(SWIGTYPE_p_f_p_q_const__void___int64_p_void____int64 value) {
    libsndfileJNI.SF_VIRTUAL_IO_write_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__void___int64_p_void____int64.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__void___int64_p_void____int64 getWrite() {
    long cPtr = libsndfileJNI.SF_VIRTUAL_IO_write_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__void___int64_p_void____int64(cPtr, false);
  }

  public void setTell(SWIGTYPE_p_f_p_void____int64 value) {
    libsndfileJNI.SF_VIRTUAL_IO_tell_set(swigCPtr, this, SWIGTYPE_p_f_p_void____int64.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void____int64 getTell() {
    long cPtr = libsndfileJNI.SF_VIRTUAL_IO_tell_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void____int64(cPtr, false);
  }

  public SF_VIRTUAL_IO() {
    this(libsndfileJNI.new_SF_VIRTUAL_IO(), true);
  }

}
