/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd;

public interface libsndfileConstants {
  public final static int SF_FORMAT_WAV = libsndfileJNI.SF_FORMAT_WAV_get();
  public final static int SF_FORMAT_AIFF = libsndfileJNI.SF_FORMAT_AIFF_get();
  public final static int SF_FORMAT_AU = libsndfileJNI.SF_FORMAT_AU_get();
  public final static int SF_FORMAT_RAW = libsndfileJNI.SF_FORMAT_RAW_get();
  public final static int SF_FORMAT_PAF = libsndfileJNI.SF_FORMAT_PAF_get();
  public final static int SF_FORMAT_SVX = libsndfileJNI.SF_FORMAT_SVX_get();
  public final static int SF_FORMAT_NIST = libsndfileJNI.SF_FORMAT_NIST_get();
  public final static int SF_FORMAT_VOC = libsndfileJNI.SF_FORMAT_VOC_get();
  public final static int SF_FORMAT_IRCAM = libsndfileJNI.SF_FORMAT_IRCAM_get();
  public final static int SF_FORMAT_W64 = libsndfileJNI.SF_FORMAT_W64_get();
  public final static int SF_FORMAT_MAT4 = libsndfileJNI.SF_FORMAT_MAT4_get();
  public final static int SF_FORMAT_MAT5 = libsndfileJNI.SF_FORMAT_MAT5_get();
  public final static int SF_FORMAT_PVF = libsndfileJNI.SF_FORMAT_PVF_get();
  public final static int SF_FORMAT_XI = libsndfileJNI.SF_FORMAT_XI_get();
  public final static int SF_FORMAT_HTK = libsndfileJNI.SF_FORMAT_HTK_get();
  public final static int SF_FORMAT_SDS = libsndfileJNI.SF_FORMAT_SDS_get();
  public final static int SF_FORMAT_AVR = libsndfileJNI.SF_FORMAT_AVR_get();
  public final static int SF_FORMAT_WAVEX = libsndfileJNI.SF_FORMAT_WAVEX_get();
  public final static int SF_FORMAT_SD2 = libsndfileJNI.SF_FORMAT_SD2_get();
  public final static int SF_FORMAT_FLAC = libsndfileJNI.SF_FORMAT_FLAC_get();
  public final static int SF_FORMAT_CAF = libsndfileJNI.SF_FORMAT_CAF_get();
  public final static int SF_FORMAT_WVE = libsndfileJNI.SF_FORMAT_WVE_get();
  public final static int SF_FORMAT_OGG = libsndfileJNI.SF_FORMAT_OGG_get();
  public final static int SF_FORMAT_MPC2K = libsndfileJNI.SF_FORMAT_MPC2K_get();
  public final static int SF_FORMAT_RF64 = libsndfileJNI.SF_FORMAT_RF64_get();
  public final static int SF_FORMAT_PCM_S8 = libsndfileJNI.SF_FORMAT_PCM_S8_get();
  public final static int SF_FORMAT_PCM_16 = libsndfileJNI.SF_FORMAT_PCM_16_get();
  public final static int SF_FORMAT_PCM_24 = libsndfileJNI.SF_FORMAT_PCM_24_get();
  public final static int SF_FORMAT_PCM_32 = libsndfileJNI.SF_FORMAT_PCM_32_get();
  public final static int SF_FORMAT_PCM_U8 = libsndfileJNI.SF_FORMAT_PCM_U8_get();
  public final static int SF_FORMAT_FLOAT = libsndfileJNI.SF_FORMAT_FLOAT_get();
  public final static int SF_FORMAT_DOUBLE = libsndfileJNI.SF_FORMAT_DOUBLE_get();
  public final static int SF_FORMAT_ULAW = libsndfileJNI.SF_FORMAT_ULAW_get();
  public final static int SF_FORMAT_ALAW = libsndfileJNI.SF_FORMAT_ALAW_get();
  public final static int SF_FORMAT_IMA_ADPCM = libsndfileJNI.SF_FORMAT_IMA_ADPCM_get();
  public final static int SF_FORMAT_MS_ADPCM = libsndfileJNI.SF_FORMAT_MS_ADPCM_get();
  public final static int SF_FORMAT_GSM610 = libsndfileJNI.SF_FORMAT_GSM610_get();
  public final static int SF_FORMAT_VOX_ADPCM = libsndfileJNI.SF_FORMAT_VOX_ADPCM_get();
  public final static int SF_FORMAT_G721_32 = libsndfileJNI.SF_FORMAT_G721_32_get();
  public final static int SF_FORMAT_G723_24 = libsndfileJNI.SF_FORMAT_G723_24_get();
  public final static int SF_FORMAT_G723_40 = libsndfileJNI.SF_FORMAT_G723_40_get();
  public final static int SF_FORMAT_DWVW_12 = libsndfileJNI.SF_FORMAT_DWVW_12_get();
  public final static int SF_FORMAT_DWVW_16 = libsndfileJNI.SF_FORMAT_DWVW_16_get();
  public final static int SF_FORMAT_DWVW_24 = libsndfileJNI.SF_FORMAT_DWVW_24_get();
  public final static int SF_FORMAT_DWVW_N = libsndfileJNI.SF_FORMAT_DWVW_N_get();
  public final static int SF_FORMAT_DPCM_8 = libsndfileJNI.SF_FORMAT_DPCM_8_get();
  public final static int SF_FORMAT_DPCM_16 = libsndfileJNI.SF_FORMAT_DPCM_16_get();
  public final static int SF_FORMAT_VORBIS = libsndfileJNI.SF_FORMAT_VORBIS_get();
  public final static int SF_ENDIAN_FILE = libsndfileJNI.SF_ENDIAN_FILE_get();
  public final static int SF_ENDIAN_LITTLE = libsndfileJNI.SF_ENDIAN_LITTLE_get();
  public final static int SF_ENDIAN_BIG = libsndfileJNI.SF_ENDIAN_BIG_get();
  public final static int SF_ENDIAN_CPU = libsndfileJNI.SF_ENDIAN_CPU_get();
  public final static int SF_FORMAT_SUBMASK = libsndfileJNI.SF_FORMAT_SUBMASK_get();
  public final static int SF_FORMAT_TYPEMASK = libsndfileJNI.SF_FORMAT_TYPEMASK_get();
  public final static int SF_FORMAT_ENDMASK = libsndfileJNI.SF_FORMAT_ENDMASK_get();

  public final static int SFC_GET_LIB_VERSION = libsndfileJNI.SFC_GET_LIB_VERSION_get();
  public final static int SFC_GET_LOG_INFO = libsndfileJNI.SFC_GET_LOG_INFO_get();
  public final static int SFC_GET_CURRENT_SF_INFO = libsndfileJNI.SFC_GET_CURRENT_SF_INFO_get();
  public final static int SFC_GET_NORM_DOUBLE = libsndfileJNI.SFC_GET_NORM_DOUBLE_get();
  public final static int SFC_GET_NORM_FLOAT = libsndfileJNI.SFC_GET_NORM_FLOAT_get();
  public final static int SFC_SET_NORM_DOUBLE = libsndfileJNI.SFC_SET_NORM_DOUBLE_get();
  public final static int SFC_SET_NORM_FLOAT = libsndfileJNI.SFC_SET_NORM_FLOAT_get();
  public final static int SFC_SET_SCALE_FLOAT_INT_READ = libsndfileJNI.SFC_SET_SCALE_FLOAT_INT_READ_get();
  public final static int SFC_SET_SCALE_INT_FLOAT_WRITE = libsndfileJNI.SFC_SET_SCALE_INT_FLOAT_WRITE_get();
  public final static int SFC_GET_SIMPLE_FORMAT_COUNT = libsndfileJNI.SFC_GET_SIMPLE_FORMAT_COUNT_get();
  public final static int SFC_GET_SIMPLE_FORMAT = libsndfileJNI.SFC_GET_SIMPLE_FORMAT_get();
  public final static int SFC_GET_FORMAT_INFO = libsndfileJNI.SFC_GET_FORMAT_INFO_get();
  public final static int SFC_GET_FORMAT_MAJOR_COUNT = libsndfileJNI.SFC_GET_FORMAT_MAJOR_COUNT_get();
  public final static int SFC_GET_FORMAT_MAJOR = libsndfileJNI.SFC_GET_FORMAT_MAJOR_get();
  public final static int SFC_GET_FORMAT_SUBTYPE_COUNT = libsndfileJNI.SFC_GET_FORMAT_SUBTYPE_COUNT_get();
  public final static int SFC_GET_FORMAT_SUBTYPE = libsndfileJNI.SFC_GET_FORMAT_SUBTYPE_get();
  public final static int SFC_CALC_SIGNAL_MAX = libsndfileJNI.SFC_CALC_SIGNAL_MAX_get();
  public final static int SFC_CALC_NORM_SIGNAL_MAX = libsndfileJNI.SFC_CALC_NORM_SIGNAL_MAX_get();
  public final static int SFC_CALC_MAX_ALL_CHANNELS = libsndfileJNI.SFC_CALC_MAX_ALL_CHANNELS_get();
  public final static int SFC_CALC_NORM_MAX_ALL_CHANNELS = libsndfileJNI.SFC_CALC_NORM_MAX_ALL_CHANNELS_get();
  public final static int SFC_GET_SIGNAL_MAX = libsndfileJNI.SFC_GET_SIGNAL_MAX_get();
  public final static int SFC_GET_MAX_ALL_CHANNELS = libsndfileJNI.SFC_GET_MAX_ALL_CHANNELS_get();
  public final static int SFC_SET_ADD_PEAK_CHUNK = libsndfileJNI.SFC_SET_ADD_PEAK_CHUNK_get();
  public final static int SFC_SET_ADD_HEADER_PAD_CHUNK = libsndfileJNI.SFC_SET_ADD_HEADER_PAD_CHUNK_get();
  public final static int SFC_UPDATE_HEADER_NOW = libsndfileJNI.SFC_UPDATE_HEADER_NOW_get();
  public final static int SFC_SET_UPDATE_HEADER_AUTO = libsndfileJNI.SFC_SET_UPDATE_HEADER_AUTO_get();
  public final static int SFC_FILE_TRUNCATE = libsndfileJNI.SFC_FILE_TRUNCATE_get();
  public final static int SFC_SET_RAW_START_OFFSET = libsndfileJNI.SFC_SET_RAW_START_OFFSET_get();
  public final static int SFC_SET_DITHER_ON_WRITE = libsndfileJNI.SFC_SET_DITHER_ON_WRITE_get();
  public final static int SFC_SET_DITHER_ON_READ = libsndfileJNI.SFC_SET_DITHER_ON_READ_get();
  public final static int SFC_GET_DITHER_INFO_COUNT = libsndfileJNI.SFC_GET_DITHER_INFO_COUNT_get();
  public final static int SFC_GET_DITHER_INFO = libsndfileJNI.SFC_GET_DITHER_INFO_get();
  public final static int SFC_GET_EMBED_FILE_INFO = libsndfileJNI.SFC_GET_EMBED_FILE_INFO_get();
  public final static int SFC_SET_CLIPPING = libsndfileJNI.SFC_SET_CLIPPING_get();
  public final static int SFC_GET_CLIPPING = libsndfileJNI.SFC_GET_CLIPPING_get();
  public final static int SFC_GET_INSTRUMENT = libsndfileJNI.SFC_GET_INSTRUMENT_get();
  public final static int SFC_SET_INSTRUMENT = libsndfileJNI.SFC_SET_INSTRUMENT_get();
  public final static int SFC_GET_LOOP_INFO = libsndfileJNI.SFC_GET_LOOP_INFO_get();
  public final static int SFC_GET_BROADCAST_INFO = libsndfileJNI.SFC_GET_BROADCAST_INFO_get();
  public final static int SFC_SET_BROADCAST_INFO = libsndfileJNI.SFC_SET_BROADCAST_INFO_get();
  public final static int SFC_GET_CHANNEL_MAP_INFO = libsndfileJNI.SFC_GET_CHANNEL_MAP_INFO_get();
  public final static int SFC_SET_CHANNEL_MAP_INFO = libsndfileJNI.SFC_SET_CHANNEL_MAP_INFO_get();
  public final static int SFC_RAW_DATA_NEEDS_ENDSWAP = libsndfileJNI.SFC_RAW_DATA_NEEDS_ENDSWAP_get();
  public final static int SFC_WAVEX_SET_AMBISONIC = libsndfileJNI.SFC_WAVEX_SET_AMBISONIC_get();
  public final static int SFC_WAVEX_GET_AMBISONIC = libsndfileJNI.SFC_WAVEX_GET_AMBISONIC_get();
  public final static int SFC_SET_VBR_ENCODING_QUALITY = libsndfileJNI.SFC_SET_VBR_ENCODING_QUALITY_get();
  public final static int SFC_TEST_IEEE_FLOAT_REPLACE = libsndfileJNI.SFC_TEST_IEEE_FLOAT_REPLACE_get();
  public final static int SFC_SET_ADD_DITHER_ON_WRITE = libsndfileJNI.SFC_SET_ADD_DITHER_ON_WRITE_get();
  public final static int SFC_SET_ADD_DITHER_ON_READ = libsndfileJNI.SFC_SET_ADD_DITHER_ON_READ_get();

  public final static int SF_STR_TITLE = libsndfileJNI.SF_STR_TITLE_get();
  public final static int SF_STR_COPYRIGHT = libsndfileJNI.SF_STR_COPYRIGHT_get();
  public final static int SF_STR_SOFTWARE = libsndfileJNI.SF_STR_SOFTWARE_get();
  public final static int SF_STR_ARTIST = libsndfileJNI.SF_STR_ARTIST_get();
  public final static int SF_STR_COMMENT = libsndfileJNI.SF_STR_COMMENT_get();
  public final static int SF_STR_DATE = libsndfileJNI.SF_STR_DATE_get();
  public final static int SF_STR_ALBUM = libsndfileJNI.SF_STR_ALBUM_get();
  public final static int SF_STR_LICENSE = libsndfileJNI.SF_STR_LICENSE_get();
  public final static int SF_STR_TRACKNUMBER = libsndfileJNI.SF_STR_TRACKNUMBER_get();
  public final static int SF_STR_GENRE = libsndfileJNI.SF_STR_GENRE_get();

  public final static int SF_FALSE = libsndfileJNI.SF_FALSE_get();
  public final static int SF_TRUE = libsndfileJNI.SF_TRUE_get();
  public final static int SFM_READ = libsndfileJNI.SFM_READ_get();
  public final static int SFM_WRITE = libsndfileJNI.SFM_WRITE_get();
  public final static int SFM_RDWR = libsndfileJNI.SFM_RDWR_get();
  public final static int SF_AMBISONIC_NONE = libsndfileJNI.SF_AMBISONIC_NONE_get();
  public final static int SF_AMBISONIC_B_FORMAT = libsndfileJNI.SF_AMBISONIC_B_FORMAT_get();

  public final static int SF_ERR_NO_ERROR = libsndfileJNI.SF_ERR_NO_ERROR_get();
  public final static int SF_ERR_UNRECOGNISED_FORMAT = libsndfileJNI.SF_ERR_UNRECOGNISED_FORMAT_get();
  public final static int SF_ERR_SYSTEM = libsndfileJNI.SF_ERR_SYSTEM_get();
  public final static int SF_ERR_MALFORMED_FILE = libsndfileJNI.SF_ERR_MALFORMED_FILE_get();
  public final static int SF_ERR_UNSUPPORTED_ENCODING = libsndfileJNI.SF_ERR_UNSUPPORTED_ENCODING_get();

  public final static int SF_CHANNEL_MAP_INVALID = libsndfileJNI.SF_CHANNEL_MAP_INVALID_get();
  public final static int SF_CHANNEL_MAP_MONO = libsndfileJNI.SF_CHANNEL_MAP_MONO_get();
  public final static int SF_CHANNEL_MAP_LEFT = libsndfileJNI.SF_CHANNEL_MAP_LEFT_get();
  public final static int SF_CHANNEL_MAP_RIGHT = libsndfileJNI.SF_CHANNEL_MAP_RIGHT_get();
  public final static int SF_CHANNEL_MAP_CENTER = libsndfileJNI.SF_CHANNEL_MAP_CENTER_get();
  public final static int SF_CHANNEL_MAP_FRONT_LEFT = libsndfileJNI.SF_CHANNEL_MAP_FRONT_LEFT_get();
  public final static int SF_CHANNEL_MAP_FRONT_RIGHT = libsndfileJNI.SF_CHANNEL_MAP_FRONT_RIGHT_get();
  public final static int SF_CHANNEL_MAP_FRONT_CENTER = libsndfileJNI.SF_CHANNEL_MAP_FRONT_CENTER_get();
  public final static int SF_CHANNEL_MAP_REAR_CENTER = libsndfileJNI.SF_CHANNEL_MAP_REAR_CENTER_get();
  public final static int SF_CHANNEL_MAP_REAR_LEFT = libsndfileJNI.SF_CHANNEL_MAP_REAR_LEFT_get();
  public final static int SF_CHANNEL_MAP_REAR_RIGHT = libsndfileJNI.SF_CHANNEL_MAP_REAR_RIGHT_get();
  public final static int SF_CHANNEL_MAP_LFE = libsndfileJNI.SF_CHANNEL_MAP_LFE_get();
  public final static int SF_CHANNEL_MAP_FRONT_LEFT_OF_CENTER = libsndfileJNI.SF_CHANNEL_MAP_FRONT_LEFT_OF_CENTER_get();
  public final static int SF_CHANNEL_MAP_FRONT_RIGHT_OF_CENTER = libsndfileJNI.SF_CHANNEL_MAP_FRONT_RIGHT_OF_CENTER_get();
  public final static int SF_CHANNEL_MAP_SIDE_LEFT = libsndfileJNI.SF_CHANNEL_MAP_SIDE_LEFT_get();
  public final static int SF_CHANNEL_MAP_SIDE_RIGHT = libsndfileJNI.SF_CHANNEL_MAP_SIDE_RIGHT_get();
  public final static int SF_CHANNEL_MAP_TOP_CENTER = libsndfileJNI.SF_CHANNEL_MAP_TOP_CENTER_get();
  public final static int SF_CHANNEL_MAP_TOP_FRONT_LEFT = libsndfileJNI.SF_CHANNEL_MAP_TOP_FRONT_LEFT_get();
  public final static int SF_CHANNEL_MAP_TOP_FRONT_RIGHT = libsndfileJNI.SF_CHANNEL_MAP_TOP_FRONT_RIGHT_get();
  public final static int SF_CHANNEL_MAP_TOP_FRONT_CENTER = libsndfileJNI.SF_CHANNEL_MAP_TOP_FRONT_CENTER_get();
  public final static int SF_CHANNEL_MAP_TOP_REAR_LEFT = libsndfileJNI.SF_CHANNEL_MAP_TOP_REAR_LEFT_get();
  public final static int SF_CHANNEL_MAP_TOP_REAR_RIGHT = libsndfileJNI.SF_CHANNEL_MAP_TOP_REAR_RIGHT_get();
  public final static int SF_CHANNEL_MAP_TOP_REAR_CENTER = libsndfileJNI.SF_CHANNEL_MAP_TOP_REAR_CENTER_get();
  public final static int SF_CHANNEL_MAP_AMBISONIC_B_W = libsndfileJNI.SF_CHANNEL_MAP_AMBISONIC_B_W_get();
  public final static int SF_CHANNEL_MAP_AMBISONIC_B_X = libsndfileJNI.SF_CHANNEL_MAP_AMBISONIC_B_X_get();
  public final static int SF_CHANNEL_MAP_AMBISONIC_B_Y = libsndfileJNI.SF_CHANNEL_MAP_AMBISONIC_B_Y_get();
  public final static int SF_CHANNEL_MAP_AMBISONIC_B_Z = libsndfileJNI.SF_CHANNEL_MAP_AMBISONIC_B_Z_get();
  public final static int SF_CHANNEL_MAP_MAX = libsndfileJNI.SF_CHANNEL_MAP_MAX_get();

  public final static long SF_COUNT_MAX = libsndfileJNI.SF_COUNT_MAX_get();
  public final static int SFD_DEFAULT_LEVEL = libsndfileJNI.SFD_DEFAULT_LEVEL_get();
  public final static int SFD_CUSTOM_LEVEL = libsndfileJNI.SFD_CUSTOM_LEVEL_get();
  public final static int SFD_NO_DITHER = libsndfileJNI.SFD_NO_DITHER_get();
  public final static int SFD_WHITE = libsndfileJNI.SFD_WHITE_get();
  public final static int SFD_TRIANGULAR_PDF = libsndfileJNI.SFD_TRIANGULAR_PDF_get();

  public final static int SF_LOOP_NONE = libsndfileJNI.SF_LOOP_NONE_get();
  public final static int SF_LOOP_FORWARD = libsndfileJNI.SF_LOOP_FORWARD_get();
  public final static int SF_LOOP_BACKWARD = libsndfileJNI.SF_LOOP_BACKWARD_get();
  public final static int SF_LOOP_ALTERNATING = libsndfileJNI.SF_LOOP_ALTERNATING_get();

}
