/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd;

public class SWIGTYPE_p_f_p_void____int64 {
  private long swigCPtr;

  protected SWIGTYPE_p_f_p_void____int64(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_void____int64() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_void____int64 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

